export const CN = {
  'erase' : '删除',
  'expand': '开花',
  'collapse': '威尔特',
  'move' : '移动',
  'drag' : '移动',
  'and': '和',
  '-': '-',
  '+': '+',
  'Abbreviation': '缩写',
  'About': '大约',
  'Add Content': '加入内容',
  'Add New Topic with Style of This Palette': '添加新的主题与此调色板风格',
  'Add Topic': '添加主题',
  'Adjust Size': '调整大小',
  'Align Horizontal': '对齐水平',
  'Align Vertical': '垂直对齐',
  'All': '所有',
  'Amoeba': '变形虫',
  'Anchor': '锚',
  'Anchor Mode': '锚模式',
  'Angle': '角',
  'Anonymous Model': '匿名模式',
  'Anonyous': '匿名',
  'Any unsaved changes will be lost': '任何未保存的更改将丢失',
  'Are you absolutely sure you want to leave': '你真的确认要离开',
  'Are you sure you want to delete the following': '您确定要删除以下',
  'Are you sure you want to delete this notebook?': '你确定你要删除这台笔记本？',
  'Are you sure you want to merge': '你确定你要合并',
  'Arrow Head': '箭头',
  'Associatins': 'Associatins',
  'Association': '联想',
  'Association Role': '协会的作用',
  'AUGMENT': '扩大',
  'Blank': '空白',
  'Bloom': '开花',
  'Bloom All Direction': '布鲁姆所有方向',
  'Bloom by Direction': '布鲁姆通过方向',
  'Blue Memo': '蓝备忘录',
  'Cancel': '取消',
  'Close': '关闭',
  'Change': '变化',
  'Change Password': '更改密码',
  'Chat Mode': '聊天模式',
  'CIRCLE': '圈',
  'Citation': '引文',
  'Class': '类',
  'Clear': '明确',
  'Clear Chat Nodes': '清除聊天节点',
  'Clear Screen': '清除屏幕',
  'Clear Selection': '清除选择',
  'Clone': '克隆',
  'Cloud mode editing': '云模式编辑',
  'Collabolation': 'Collabolation',
  'Color': '颜色',
  'COMMIT': 'COMMIT',
  'Content': '内容',
  'Resource': '内容',
  'CONTENTS URL': '内容URL',
  'Control Buttons': '控制按钮',
  'Copy': '复制',
  'Copy & Paste': '复制和粘贴',
  'Copyright': '版权',
  'Create & Edit': '创建和编辑',
  'Create Account': '创建账户',
  'Create New': '新',
  'Creator': '创造者',
  'Curve': '曲线',
  'Curve/Line': '曲线/线',
  'Cut': '切',
  'Dashed': '虚线',
  'Date': '日期',
  'Date Picker': '日期选取器',
  'defined by': '通过定义',
  'Delete': '删除',
  'Deleting information': '删除信息',
  'Dialog': '对话',
  'Diameter': '直径',
  'Do you want create new note?': '你确定你要做出新的笔记本电脑？',
  'Dotted': '点',
  'Download': '下载',
  'Downloading information': '下载信息',
  'Drawing Mode': '绘图模式',
  'Dynamic Drawing': '动态图',
  'e-Book List': '电子书列表',
  'e-Books': '电子书',
  'Edge': '边缘',
  'Edge Shape': '边缘形状',
  'Edit': '编辑',
  'Edit(s) has been made.': '編輯已完成',
  'Do you want to save edit(s)?': '你想保存编辑吗？',
  'Edit Flock': '编辑羊群',
  'Edit Memo': '编辑备注',
  'Edit Style': '编辑样式',
  'Editable Mode': '编辑模式',
  'Editing': '编辑',
  'Erase': '抹去',
  'Failed': '失败',
  'File Deleted': '文件中删除',
  'File Upload': '文件上传',
  'Filter': '过滤器',
  'Filter Association': '过滤器协会',
  'Filter Topic': '过滤器主题',
  'Find': '发现',
  'Fixation': '固定术',
  'Flock': '群',
  'Font': '字形',
  'Force All Fixed': '强制所有固定',
  'Forgot Password?': '忘记密码？',
  'Free Mode': '免费模式',
  'Get Selected Content Style': '获取所选内容风格',
  'Get Selected Edge Style': '获取选边样式',
  'Get Style of Selected Item': '获取所选项目的风格',
  'Go to': '到',
  'Green Memo': '绿色备忘录',
  'Group': '组',
  'Height': '高度',
  'Hidden': '隐',
  'Hide': '隐藏',
  'Hide All': '全部隐藏',
  'Hide Memo': '隐藏备忘录',
  'Hide Names': '隐藏名称',
  'Horizontal Axis': '水平轴',
  'Horizontal Equal': '横向平等',
  'Image': '图像',
  'In case you cannot load iframe contents': '如果您不能加载的iframe内容',
  'Introduction': '介绍',
  'item(s) listed below': '下面列出的项目（S）',
  'Join': '加入',
  'Keyword': '关键词',
  'Label': '标签',
  'Layout Topics': '版面主题',
  'Leave': '离开',
  'List': '名单',
  'List of Notebooks': '笔记本一览',
  'Load': '加载',
  'Loading information': '加载信息',
  'Local editing mode': '本地编辑模式',
  'Login': '登录',
  'LOGIN FAILED': '登录失败',
  'Logout': '注销',
  'maximum size is': '最大尺寸为',
  'members': '成员',
  'Memo': '备忘录',
  'Merge': '合并',
  'Miniature': '微型',
  'Miniature Canvas': '微型帆布',
  'minimum size is': '最小尺寸是',
  'Model': '型号',
  'More': '更多',
  'Multiple Lines': '多行',
  'Name': '名字',
  'New': '新',
  'New Axis': '新中轴线',
  'New Child Topic': '新的儿童主题',
  'New Citation': '新引',
  'Add Resource': '新的内容',
  'New Flock': '新的羊群',
  'Add Memo': '新的备忘录',
  'New Note': '新',
  'New Page': '新页面',
  'New Topic': '新主题',
  'Not Found.': '未找到',
  'Not Owner': '没有业主',
  'Note': '注意',
  'Notebook': '笔记本',
  'Notebook name': '笔记本电脑的名字',
  'Notebook saved in cloud as': '笔记本电脑保存在云中',
  'Notice': '通知',
  'Open': '打开',
  'ELLIPSE': '椭圆形',
  'Overwrite': '覆盖',
  'Page Name': '页的备忘录',
  'Pages': '网页',
  'Password': '密码',
  'Paste': '贴',
  'Pause': '暂停',
  'Pink Memo': '粉红色的备忘录',
  'Play': '玩',
  'Please log in.': '请登录。',
  'Please save': '请妥善保存',
  'please wait': '请稍候',
  'Post Page to Chat': '帖子页聊天',
  'Post This Page': '发布此页',
  'Presentation': '介绍',
  'Prev': '上一页',
  'Private': '私人',
  'Project': '工程',
  'Public': '公开',
  'PUBLIC Notebooks': 'PUBLIC笔记本电脑',
  'Radius': '半径',
  'Randomize Layout': '布局随机化',
  'RECTANGLE': '矩形',
  'Redo': '重做',
  'Reference': '参考',
  'Reflesh Chat Nodes': 'Reflesh聊天节点',
  'Refresh': '刷新',
  'Registered Site': '注册网站',
  'Release All Fixed': '释放所有固定',
  'Relevant Page': '相关页面',
  'Reload': '刷新',
  'Reset View': '重置浏览',
  'Reverse': '反',
  'Role': '角色',
  'Root': '根',
  'ROUNDED': '圆角',
  'SAMBUICHI PEs Office': 'SAMBUICHI PE办公室',
  'Save': '保存',
  'Save As': '保存为',
  'Save New': '保存新',
  'Save Notebook': '保存笔记本',
  'Scatter': '分散',
  'Scope': '范围',
  'Screenshot': '截图',
  'Search': '搜索',
  'Search Filter': ' 搜索过滤器',
  'Search occurrence for the given (sub)string.': '搜索事件为给定的（子）字符串。',
  'Search the note for the given (sub)string.': '搜索注意对于给定的（子）字符串。',
  'Search topic for the given (sub)string.': '搜索话题，给定（子）字符串。',
  'Select': '选择',
  'Select All': '全选',
  'Select Content': '选择内容',
  'Select Topic': '选择主题',
  'separated with spaces': '用空格隔开',
  'Setting Options': '设置选项',
  'Shape': '形状',
  'Short Cuts': '捷径',
  'Shortcut Keys': '快捷键',
  'Show': '演出',
  'Show All': '显示全部',
  'Size': '尺寸',
  'Solid': '固',
  'Start': '开始',
  'Static Drawing': '静态图',
  'Straight': '直行',
  'Subwindow': '子窗口',
  'Text': '文本',
  'Text Color': '文字颜色',
  'Text File': '文字档',
  'The notebook was deleted successfully.': '笔记本电脑被成功删除。',
  'The selected notebook could not be deleted from the cloud service!': '所选择的笔记本电脑无法从云服务中删除！',
  'The selected notebook could not be loaded from the cloud service!': '所选的笔记本无法从云服务装！',
  'This is the Navigation Window.': '这是导航窗口。\ n它总是由\钠红色轮廓显示整个笔记本\ nwith显示当前视口。点击\ n移动视口。',
  'THUMBNAIL': '缩略图',
  'Timemachine': '时间机器',
  'Toggle': '切换',
  'Toggle Anchor': '切换锚',
  'Toggle Chat': '切换聊天',
  'Toggle Fix': '切换修复',
  'Toggle Search': '切换搜索',
  'Topic': '话题',
  'Topic Categoly': '主题分类',
  'Topics ': '主题',
  'Tree': '树',
  'Try again after logging in': '登录后再试',
  'Tutorial': '教程',
  'Type': '类型',
  'Un/Directed': 'UN /导演',
  'undefined': '未定义',
  'Undirected Bloom': '无向布鲁姆',
  'Undo': '复原',
  'Upload': '上传',
  'Upload File': '上传文件',
  'Upload Model ': '上传模式',
  'Upload Pdf Annotations': '上传PDF注释',
  'Uploaded': '上传',
  'URL': 'URL',
  'User ID': '用户身份',
  'User Name': '用户名',
  'Vertical Equal Int.': '纵向平等诠释。',
  'View': '视图',
  'Visible': '可见',
  'Width': '宽度',
  'Wilt': '威尔特',
  'World Encyclopedia': '世界百科全书',
  'WuWei & PDF Annotation': '無為和PDF注释',
  'WuWei Manual': '無為手册',
  'WuWei Tutorial': '無為教程',
  'You are logged in as': '您的登录身份',
  'You may try to tap SOURCE link to view contents directly.': '您可以尝试挖掘源链接，直接查看内容。',
  'You need to log in before saving. Try to save again after logging in!': '您需要在保存之前登录。尝试登录后再次保存！',
  'You need to log in to reach your private notebooks': '您需要登录到您的私人笔记本电脑',
  'You need to log in to use notebooks': '您需要登录才能使用笔记本电脑',
  'Your PRIVATE Notebooks': '你的私人笔记本电脑',
  'Zoom': '放大',
  'Create a personal content collection and annotate it.': '创建个人内容集并对其进行注释',
  'Visual notes will help you organize your thoughts.': '视觉笔记将帮助您组织您的想法'
};
