export const EN = {
  'erase' : 'Erase',
  'expand': 'Expand',
  'collapse': 'Collapse',
  'move' : 'move',
  'drag' : 'move',
  'and': 'and',
  '-': '-',
  '+': '+',
  'Abbreviation': 'Abbreviation',
  'About': 'About',
  'Add Content': 'Add Content',
  'Add New Topic with Style of This Palette': 'Add New Topic with Style of This Palette',
  'Add Topic': 'Add Topic',
  'Adjust Size': 'Adjust Size',
  'Align Horizontal': 'Align Horizontal',
  'Align Vertical': 'Align Vertical',
  'All': 'All',
  'Amoeba': 'Amoeba',
  'Anchor': 'Anchor',
  'Anchor Mode': 'Anchor Mode',
  'Angle': 'Angle',
  'Anonymous Model': 'Anonymous Model',
  'Anonyous': 'Anonyous',
  'Any unsaved changes will be lost': 'Any unsaved changes will be lost',
  'Are you absolutely sure you want to leave': 'Are you absolutely sure you want to leave',
  'Are you sure you want to delete the following': 'Are you sure you want to delete the following',
  'Are you sure you want to delete this notebook?': 'Are you sure you want to delete this notebook?',
  'Are you sure you want to merge': 'Are you sure you want to merge',
  'Arrow Head': 'Arrow Head',
  'Associatins': 'Associatins',
  'Association': 'Association',
  'Association Role': 'Association Role',
  'AUGMENT': 'AUGMENT',
  'Blank': 'Blank',
  'Bloom': 'Expand',
  'Bloom All Direction': 'Bloom All Direction',
  'Bloom by Direction': 'Bloom by Direction',
  'Blue Memo': 'Blue Memo',
  'Cancel': 'Cancel',
  'Close': 'Close',
  'Change': 'Change',
  'Change Password': 'Change Password',
  'Chat Mode': 'Chat Mode',
  'CIRCLE': 'CIRCLE',
  'Citation': 'Citation',
  'Class': 'Class',
  'Clear': 'Clear',
  'Clear Chat Nodes': 'Clear Chat Nodes',
  'Clear Screen': 'Clear Screen',
  'Clear Selection': 'Clear Selection',
  'Clone': 'Clone',
  'Cloud mode editing': 'Cloud mode editing',
  'Collabolation': 'Collabolation',
  'Color': 'Color',
  'COMMIT': 'COMMIT',
  'Content': 'Content',
  'Resource': 'Resource',
  'CONTENTS URL': 'CONTENTS URL',
  'Control Buttons': 'Control Buttons',
  'Copy': 'Copy',
  'Copy & Paste': 'Copy & Paste',
  'Copyright': 'Copyright',
  'Create & Edit': 'Create & Edit',
  'Create Account': 'Create Account',
  'Create New': 'Create New',
  'Creator': 'Creator',
  'Curve': 'Curve',
  'Curve/Line': 'Curve/Line',
  'Cut': 'Cut',
  'Dashed': 'Dashed',
  'Date': 'Date',
  'Date Picker': 'Date Picker',
  'defined by': 'defined by',
  'Delete': 'Delete',
  'Deleting information': 'Deleting information',
  'Dialog': 'Dialog',
  'Diameter': 'Diameter',
  'Do you want create new note?': 'Do you want create new note?',
  'Dotted': 'Dotted',
  'Download': 'Download',
  'Downloading information': 'Downloading information',
  'Drawing Mode': 'Drawing Mode',
  'Dynamic Drawing': 'Dynamic Drawing',
  'e-Book List': 'e-Book List',
  'e-Books': 'e-Books',
  'Edge': 'Edge',
  'Edge Shape': 'Edge Shape',
  'Edit': 'Edit',
  'Edit(s) has been made.': 'Edit(s) has been made.',
  'Do you want to save edit(s)?': 'Do you want to save edit(s)?',
  'Edit Flock': 'Edit Flock',
  'Edit Memo': 'Edit Memo',
  'Edit Style': 'Edit Style',
  'Editable Mode': 'Editable Mode',
  'Editing': 'Editing',
  'Erase': 'Erase',
  'Failed': 'Failed',
  'File Deleted': 'File Deleted',
  'File Upload': 'File Upload',
  'Filter': 'Filter',
  'Filter Association': 'Filter Association',
  'Filter Topic': 'Filter Topic',
  'Find': 'Find',
  'Fixation': 'Fixation',
  'Flock': 'Flock',
  'Font': 'Font',
  'Force All Fixed': 'Force All Fixed',
  'Forgot Password?': 'Forgot Password?',
  'Free Mode': 'Free Mode',
  'Get Selected Content Style': 'Get Selected Content Style',
  'Get Selected Edge Style': 'Get Selected Edge Style',
  'Get Style of Selected Item': 'Get Style of Selected Item',
  'Go to': 'Go to',
  'Green Memo': 'Green Memo',
  'Group': 'Group',
  'Height': 'Height',
  'Hidden': 'Hidden',
  'Hide': 'Hide',
  'Hide All': 'Hide All',
  'Hide Memo': 'Hide Memo',
  'Hide Names': 'Hide Names',
  'Horizontal Axis': 'Horizontal Axis',
  'Horizontal Equal': 'Horizontal Equal',
  'Image': 'Image',
  'In case you cannot load iframe contents': 'In case you cannot load iframe contents',
  'Introduction': 'Introduction',
  'item(s) listed below': 'item(s) listed below',
  'Join': 'Join',
  'Keyword': 'Keyword',
  'Label': 'Label',
  'Layout Topics': 'Layout Topics',
  'Leave': 'Leave',
  'List': 'List',
  'List of Notebooks': 'List of Notebooks',
  'Load': 'Load',
  'Loading information': 'Loading information',
  'Local editing mode': 'Local editing mode',
  'Login': 'Login',
  'LOGIN FAILED': 'LOGIN FAILED',
  'Logout': 'Logout',
  'maximum size is': 'maximum size is',
  'members': 'members',
  'Memo': 'Memo',
  'Merge': 'Merge',
  'Miniature': 'Miniature',
  'Miniature Canvas': 'Miniature Canvas',
  'minimum size is': 'minimum size is',
  'Model': 'Model',
  'More': 'More',
  'Multiple Lines': 'Multiple Lines',
  'Name': 'Name',
  'New': 'New',
  'New Axis': 'New Axis',
  'New Child Topic': 'New Child Topic',
  'New Citation': 'New Citation',
  'Add Resource': 'Add Resource',
  'New Flock': 'New Flock',
  'Add Memo': 'Add Memo',
  'New Note': 'New Note',
  'New Page': 'New Page',
  'New Topic': 'New Topic',
  'Not Found.': 'Not Found.',
  'Not Owner': 'Not Owner',
  'Note': 'Note',
  'Notebook': 'Notebook',
  'Notebook name': 'Notebook name',
  'Notebook saved in cloud as': 'Notebook saved in cloud as',
  'Notice': 'Notice',
  'Open': 'Open',
  'ELLIPSE': 'ELLIPSE',
  'Overwrite': 'Overwrite',
  'Page Name': 'Page Name',
  'Pages': 'Pages',
  'Password': 'Password',
  'Paste': 'Paste',
  'Pause': 'Pause',
  'Pink Memo': 'Pink Memo',
  'Play': 'Play',
  'Please log in.': 'Please log in.',
  'Please save': 'Please save',
  'please wait': 'please wait',
  'Post Page to Chat': 'Post Page to Chat',
  'Post This Page': 'Post This Page',
  'Presentation': 'Presentation',
  'Prev': 'Prev.',
  'Private': 'Private',
  'Project': 'Project',
  'Public': 'Public',
  'PUBLIC Notebooks': 'PUBLIC Notebooks',
  'Radius': 'Radius',
  'Randomize Layout': 'Randomize Layout',
  'RECTANGLE': 'RECTANGLE',
  'Redo': 'Redo',
  'Reference': 'Reference',
  'Reflesh Chat Nodes': 'Reflesh Chat Nodes',
  'Refresh': 'Refresh',
  'Registered Site': 'Registered Site',
  'Release All Fixed': 'Release All Fixed',
  'Relevant Page': 'Relevant Page',
  'Reload': 'Reload',
  'Reset View': 'Reset View',
  'Reverse': 'Reverse',
  'Role': 'Role',
  'Root': 'Root',
  'ROUNDED': 'ROUNDED',
  'SAMBUICHI PEs Office': 'SAMBUICHI PEs Office',
  'Save': 'Save',
  'Save As': 'Save As',
  'Save New': 'Save New',
  'Save Notebook': 'Save Notebook',
  'Scatter': 'Scatter',
  'Scope': 'Scope',
  'Screenshot': 'Screenshot',
  'Search': 'Search',
  'Search Filter': 'Search Filter',
  'Search occurrence for the given (sub)string.': 'Search occurrence for the given (sub)string.',
  'Search the note for the given (sub)string.': 'Search the note for the given (sub)string.',
  'Search topic for the given (sub)string.': 'Search topic for the given (sub)string.',
  'Select': 'Select',
  'Select All': 'Select All',
  'Select Content': 'Select Content',
  'Select Topic': 'Select Topic',
  'separated with spaces': 'separated with spaces',
  'Setting Options': 'Setting Options',
  'Shape': 'Shape',
  'Short Cuts': 'Short Cuts',
  'Shortcut Keys': 'Shortcut Keys',
  'Show': 'Show',
  'Show All': 'Show All',
  'Size': 'Size',
  'Solid': 'Solid',
  'Start': 'Start',
  'Static Drawing': 'Static Drawing',
  'Straight': 'Straight',
  'Subwindow': 'Subwindow',
  'Text': 'Text',
  'Text Color': 'Text Color',
  'Text File': 'Text File',
  'The notebook was deleted successfully.': 'The notebook was deleted successfully.',
  'The selected notebook could not be deleted from the cloud service!': 'The selected notebook could not be deleted from the cloud service!',
  'The selected notebook could not be loaded from the cloud service!': 'The selected notebook could not be loaded from the cloud service!',
  'This is the Navigation Window.': 'This is the Navigation Window.\nIt will always show the whole notebook\nwith the current viewport shown by\na red outline. Click to\nmove the viewport.',
  'THUMBNAIL': 'THUMBNAIL',
  'Timemachine': 'Timemachine',
  'Toggle': 'Toggle',
  'Toggle Anchor': 'Toggle Anchor',
  'Toggle Chat': 'Toggle Chat',
  'Toggle Fix': 'Toggle Fix',
  'Toggle Search': 'Toggle search',
  'Topic': 'Topic',
  'Topic Categoly': 'Topic Categoly',
  'Topics ': 'Topics',
  'Tree': 'Tree',
  'Try again after logging in': 'Try again after logging in',
  'Tutorial': 'Tutorial',
  'Type': 'Type',
  'Un/Directed': 'Un/Directed',
  'undefined': 'undefined',
  'Undirected Bloom': 'Undirected Bloom',
  'Undo': 'Undo',
  'Upload': 'Upload',
  'Upload File': 'Upload File',
  'Upload Model ': 'Upload Model',
  'Upload Pdf Annotations': 'Upload Pdf Annotations',
  'Uploaded': 'Uploaded',
  'URL': 'URL',
  'User ID': 'User ID',
  'User Name': 'User Name',
  'Vertical Equal Int.': 'Vertical Equal Int.',
  'View': 'View',
  'Visible': 'Visible',
  'Width': 'Width',
  'Wilt': 'Collapse',
  'World Encyclopedia': 'World Encyclopedia',
  'WuWei & PDF Annotation': 'WuWei & PDF Annotation',
  'WuWei Manual': 'WuWei Manual',
  'WuWei Tutorial': 'WuWei Tutorial',
  'You are logged in as': 'You are logged in as',
  'You may try to tap SOURCE link to view contents directly.': 'You may try to tap SOURCE link to view contents directly.',
  'You need to log in before saving. Try to save again after logging in!': 'You need to log in before saving. Try to save again after logging in!',
  'You need to log in to reach your private notebooks': 'You need to log in to reach your private notebooks',
  'You need to log in to use notebooks': 'You need to log in to use notebooks',
  'Your PRIVATE Notebooks': 'Your PRIVATE Notebooks',
  'Zoom': 'Zoom',
  'Create a personal content collection and annotate it.': 'Create a personal content collection and annotate it.',
  'Visual notes will help you organize your thoughts.': 'Visual notes will help you organize your thoughts.'
};
