export const JA = {
  'erase': '削除',
  'expand': '開く',
  'collapse': '折りたたむ',
  'move': '移動',
  'drag': '移動',
  'and': ' 及び',
  '-': '-',
  '+': '+',
  'Abbreviation': '省略',
  'About': 'ヘルプ',
  'Add Content': 'コンテンツ追加',
  'Add New Topic with Style of This Palette': 'パレットのスタイルでトピックを追加',
  'Add Topic': 'トピック追加',
  'Adjust Size': '可変サイズ',
  'Align Horizontal': '上下中央揃え',
  'Align Vertical': '左右中央揃え',
  'All': '全て',
  'Amoeba': 'アメーバ',
  'Anchor': '固定',
  'Anchor Mode': '配置：固定モード',
  'Angle': '角度',
  'Anonymous Model': '匿名ノート',
  'Anonyous': '匿名化',
  'Any unsaved changes will be lost': '保存していない変更内容は失われます。',
  'Are you absolutely sure you want to leave': 'このページを閉じてもよろしいですか？',
  'Are you sure you want to delete the following': '次に示す要素を削除してもよろしいですか',
  'Are you sure you want to delete this notebook?': '削除してもよろしいですか？',
  'Are you sure you want to merge': '次のトピックをマージしてもよろしいですか？　',
  'Arrow Head': '矢印あり',
  'Associatins': '関連線の形',
  'Association': '関連線',
  'Association Role': '関連ロール',
  'AUGMENT': '追加',
  'Blank': '白紙',
  'Bloom': '開く',
  'Bloom All Direction': '関連線の方向によらず全て展開',
  'Bloom by Direction': '関連線の方向で展開を制限',
  'Blue Memo': '青い付箋紙',
  'Cancel': '取消',
  'Close': '閉じる',
  'Change': '変更',
  'Change Password': 'パスワード変更',
  'Chat Mode': '共同作業モード',
  'CIRCLE': '円',
  'Citation': '引用',
  'Class': '分類',
  'Clear': '消去',
  'Clear Chat Nodes': '共同作業の内容を消去しています。',
  'Clear Screen': '画面消去',
  'Clear Selection': '選択解除',
  'Clone': '複製',
  'Cloud mode editing': 'クラウドモードで編集中',
  'Collabolation': '共同作業',
  'Color': '色',
  'COMMIT': '実行',
  'Content': 'コンテンツ',
  'Resource': 'コンテンツ',
  'CONTENTS URL': 'コンテンツURL',
  'Control Buttons': 'コントロールボタン',
  'Copy': 'コピー',
  'Copy & Paste': 'コピー＆ペースト',
  'Copyright': '著作権',
  'Create & Edit': '作成と編集',
  'Create Account': 'ユーザ登録',
  'Create New': '新しく作成',
  'Creator': '作者',
  'Curve': 'やわらかい関連線',
  'Curve/Line': 'やわらかい/真直ぐな関連線',
  'Cut': 'カット',
  'Dashed': '破線',
  'Date': '日付',
  'Date Picker': '日付指定',
  'defined by': '作',
  'Delete': '削除',
  'Deleting information': '削除しています。',
  'Dialog': '対話',
  'Diameter': '直径',
  'Do you want create new note?': '新規ノートを作成しますか？',
  'Dotted': '点線',
  'Download': 'ダウンロード',
  'Downloading information': 'ダウンロードしています。',
  'Drawing Mode': '描画モード',
  'Dynamic Drawing': '動的描画',
  'e-Book List': '書籍一覧',
  'e-Books': '電子書庫',
  'Edge': '関連線',
  'Edge Shape': '線種',
  'Edit': '編集',
  'Edit(s) has been made.': '編集完了',
  'Do you want to save edit(s)?': '変更内容を保存しますか？',
  'Edit Flock': 'グループ編集',
  'Edit Memo': '付箋紙編集',
  'Edit Style': 'スタイル編集',
  'Editable Mode': '編集モード',
  'Editing': '編集中',
  'ELLIPSE': '楕円',
  'Erase': '削除',
  'Failed': 'アップロード失敗',
  'File Deleted': 'ファイル削除',
  'File Upload': 'ファイル　アップロード',
  'Filter': '絞り込み表示',
  'Filter Association': '関連線を絞り込む',
  'Filter Topic': 'トピックを絞り込む',
  'Find': '見つける',
  'Fixation': '再配置',
  'Flock': 'グループ',
  'Font': 'フォント',
  'Force All Fixed': '全てを固定',
  'Forgot Password?': 'パスワードをお忘れですか？',
  'Free Mode': '配置：遊動モード',
  'Get Selected Content Style': '選択したコンテンツのスタイル取得',
  'Get Selected Edge Style': '選択した線のスタイル取得',
  'Get Style of Selected Item': '選択した対象のスタイル取得',
  'Go to': '移動',
  'Green Memo': '緑の付箋紙',
  'Group': 'グループ',
  'Height': '高さ',
  'Hidden': '非表示',
  'Hide': '非表示',
  'Hide All': '全て非表示',
  'Hide Memo': '付箋紙非表示',
  'Hide Names': '作成者名非表示',
  'Horizontal Axis': '水平軸作成',
  'Horizontal Equal': '左右に整列',
  'Image': '画像',
  'In case you cannot load iframe contents': 'iframeの内容を表示できないときには',
  'Introduction': '説明',
  'item(s) listed below': 'トピック（コンテンツ）(下に示します)',
  'Join': 'グループに加える',
  'Keyword': 'キーワード',
  'Label': 'ラベル',
  'Layout Topics': 'トピック配置',
  'Leave': 'グループから外す',
  'List': '一覧',
  'List of Notebooks': 'ノート一覧',
  'Load': 'ロード',
  'Loading information': 'ロードしています。',
  'Local editing mode': 'オフライン編集モード',
  'Login': 'ログイン',
  'LOGIN FAILED': 'ログインできませんでした',
  'Logout': 'ログアウト',
  'maximum size is': '画像の最大サイズは',
  'members': 'グループメンバ',
  'Memo': '付箋紙',
  'Merge': 'マージ',
  'Miniature': '縮小図',
  'Miniature Canvas': '縮図　表示/非表示',
  'minimum size is': '画像の最小サイズは',
  'Model': 'モデル',
  'More': '次',
  'Multiple Lines': '複数行',
  'Name': '名前',
  'New': '新規',
  'New Axis': '新しい軸',
  'New Child Topic': '新規子トピック',
  'New Citation': '新規引用',
  'Add Resource': 'コンテンツ追加',
  'Add Memo': '付箋紙追加',
  'New Flock': '新規グループ',
  'New Note': '新しく作成',
  'New Page': 'ページ作成',
  'New Topic': '新規トピック',
  'Not Found.': '見つかりませんでした',
  'Not Owner': '作者ではありません',
  'Note': '注記',
  'Notebook': 'ノート',
  'Notebook name': 'ノート名',
  'Notebook saved in cloud as': 'ノートをクラウドに保存しました：',
  'Notice': 'お知らせ',
  'ELLIPAE': '楕円',
  'Open': '開く',
  'Overwrite': '上書き保存',
  'Page Name': '名前',
  'Pages': 'ページ操作',
  'Password': 'パスワード',
  'Paste': 'ペースト',
  'Pause': '停止',
  'Pink Memo': 'ピンクの付箋紙',
  'Play': '遊動',
  'Please log in.': 'ログインしてください',
  'Please save': '保存してください',
  'please wait': 'そのままでお待ちください。',
  'Post Page to Chat': '共同作業の内容を登録しています。',
  'Post This Page': 'ページ公開',
  'Presentation': 'プレゼンテーション',
  'Prev': '前',
  'Private': '非公開',
  'Project': 'プロジェクト',
  'Public': '公開',
  'PUBLIC Notebooks': '公開ノート一覧',
  'Radius': '半径',
  'Randomize Layout': 'ランダム配置',
  'RECTANGLE': '四角形',
  'Redo': 'やり直し',
  'Reference': '出典',
  'Reflesh Chat Nodes': '共同作業の内容を更新しています。',
  'Refresh': '更新',
  'Registered Site': '登録したサイト',
  'Release All Fixed': '全てを解放',
  'Relevant Page': '該当ページ',
  'Reload': 'ページを再読込（更新）',
  'Reset View': '中央に配置',
  'Reverse': '逆方向',
  'Role': 'ロール',
  'Root': 'ルート',
  'ROUNDED': '角丸',
  'SAMBUICHI PEs Office': '三分一技術士事務所',
  'Save': '保存',
  'Save As': '別名保存',
  'Save New': '新規登録',
  'Save Notebook': '保存',
  'Scatter': 'グループ解除',
  'Scope': 'スコープ',
  'Screenshot': '画面を印刷',
  'Search': '検索',
  'Search Filter': ' 検索文字列',
  'Search occurrence for the given (sub)string.': '検索文字列を含むコンテンツを検索します',
  'Search the note for the given (sub)string.': '検索文字列を含んだトピック候補に絞り込みます',
  'Search topic for the given (sub)string.': '検索文字列を含むトピックを検索します',
  'Select': '選択',
  'Select All': 'すべて選択',
  'Select Content': 'コンテンツを選択',
  'Select Topic': 'トピックを選択',
  'separated with spaces': '空白で分割',
  'Setting Options': 'オプション設定',
  'Shape': '形',
  'Short Cuts': 'ショートカット',
  'Shortcut Keys': 'ショートカット表示',
  'Show': '表示',
  'Show All': '全て表示',
  'Size': 'サイズ',
  'Solid': '実線',
  'Start': 'スタート',
  'Static Drawing': '静的描画',
  'Straight': '真直ぐな関連線',
  'Subwindow': '実際のコンテンツ',
  'Text': '文字',
  'Text C.': '文字色',
  'Text Color': '文字色',
  'Text File': 'テキスト　ファイル',
  'The notebook was deleted successfully.': 'ノートを削除しました。',
  'The selected notebook could not be deleted from the cloud service!': 'ノートは、クラウドから削除できませんでした！',
  'The selected notebook could not be loaded from the cloud service!': 'ノートをクラウドサービスからロードできませんでした',
  'This is the Navigation Window.': 'これは、画面移動用のウィンドウです。ここには、いつもノートの全体が表示されます。\n今見えている画面の範囲が赤い枠線で表示され、クリックするとそこを画面の中央に移動します。',
  'THUMBNAIL': '縮小画像',
  'Timemachine': '更新履歴',
  'Toggle': '表示切り替え',
  'Toggle Anchor': '固定/遊動',
  'Toggle Chat': '開始・終了',
  'Toggle Fix': '固定/遊動',
  'Toggle Search': '検索　表示/非表示',
  'Topic': 'トピック',
  'Topic Categoly': 'カテゴリー',
  'Topics ': 'トピック',
  'Tree': '階層',
  'Try again after logging in': 'ログインした後で、再度実行してください。',
  'Tutorial': 'チュートリアル',
  'Type': 'タイプ',
  'Un/Directed': '方向で展開を制限する/しない',
  'undefined': '未定義',
  'Undirected Bloom': '無方向展開',
  'Undo': '元に戻す',
  'Upload': 'アップロード',
  'Upload File': 'ファイルアップロード',
  'Upload Model ': 'アップロード',
  'Upload Pdf Annotations': 'Pdf注釈アップロード',
  'Uploaded': 'アップロード完了',
  'URL': 'URL',
  'User ID': 'ユーザID',
  'User Name': '作成者名表示',
  'Vertical Axis': '垂直軸作成',
  'Vertical Equal Int.': '上下に整列',
  'View': 'プレゼンテーション',
  'View Notebook XML': 'ノートのXML表示',
  'Visible': '表示',
  'Webcat Plus': '連想検索',
  'White Memo': '白い付箋紙',
  'Width': '幅',
  'Wilt': '折りたたむ',
  'World Encyclopedia': '世界大百科事典',
  'WuWei & PDF Annotation': 'WuWei&PDF注釈',
  'WuWei Manual': 'WuWei操作マニュアル',
  'WuWei Tutorial': 'WuWei操作説明',
  'You are logged in as': 'ようこそ',
  'You may try to tap SOURCE link to view contents directly.': '内容が表示されないときは、SOUCEのリンクを直接クリックしてください。',
  'You need to log in before saving. Try to save again after logging in!': 'ノートを保存するにはログインしている必要があります。ログインした後に再度、保存してください！',
  'You need to log in to reach your private notebooks': '非公開ノートを使用するにはログインしてください。',
  'You need to log in to use notebooks': 'ノートを使用するにはログインしてください。',
  'Your PRIVATE Notebooks': '非公開ノート一覧',
  'Zoom': 'ズーム',
  'Create a personal content collection and annotate it.': 'コンテンツコレクションを作成し注釈を付けます。',
  'Visual notes will help you organize your thoughts.': '無為ノートは、考えを整理する助けとなります。'
};
