export const KR = {
  'erase' : '지우다',
  'expand': '열기',
  'collapse': '접기',
  'move' : '이동',
  'drag' : '이동',
  'and': '및',
  '-': '-',
  '+': '+',
  'Abbreviation': '생략',
  'About': '도움말',
  'Add Content': '컨텐츠 추가',
  'Add New Topic with Style of This Palette': '팔레트 스타일로 토픽 추가',
  'Add Topic': '토픽 추가',
  'Adjust Size': '가변사이즈',
  'Align Horizontal': '상하 가운데로 정렬',
  'Align Vertical': '좌우 가운데로 정렬',
  'All': '모두',
  'Amoeba': '아메바',
  'Anchor': '고정',
  'Anchor Mode': '배치:고정모드',
  'Angle': '각도',
  'Anonymous Model': '익명 노트',
  'Anonyous': '익명화',
  'Any unsaved changes will be lost': '저장하지 않은 변경 내용은 소실됩니다.',
  'Are you absolutely sure you want to leave': '페이지를 닫을까요?',
  'Are you sure you want to delete the following': '이 요소를 삭제해도 될까요?',
  'Are you sure you want to delete this notebook?': '삭제해도 될까요?',
  'Are you sure you want to merge': '이 토픽을 병합하겠습니까?',
  'Arrow Head': '방향표시 있음',
  'Associatins': '관련선 모양',
  'Association': '관련선',
  'Association Role': '관련 역할',
  'AUGMENT': '추가',
  'Blank': '백지',
  'Bloom': '열기',
  'Bloom All Direction': '관련선 방향과 상관없이 모두 펼치기',
  'Bloom by Direction': '관련선 방향으로 펼치기 제한하기',
  'Blue Memo': '파란색 메모지',
  'Cancel': '취소',
  'Close': '닫기',
  'Change': '변경',
  'Change Password': '패스워드 변경',
  'Chat Mode': '공동작업 모드',
  'CIRCLE': '원',
  'Citation': '인용',
  'Class': '분류',
  'Clear': '삭제',
  'Clear Chat Nodes': '공동작업 내용을 삭제합니다',
  'Clear Screen': '화면삭제',
  'Clear Selection': '선택 해제',
  'Clone': '복제',
  'Cloud mode editing': '클라우드 모드로 편집중',
  'Collabolation': '공동작업',
  'Color': '색깔',
  'COMMIT': '실행',
  'Content': '컨텐츠',
  'Resource': '컨텐츠',
  'CONTENTS URL': '컨텐츠 URL',
  'Control Buttons': '컨트롤 버튼',
  'Copy': '복사',
  'Copy & Paste': '복사&붙이기',
  'Create & Edit': '작성과 편집',
  'Create Account': '사용자 등록',
  'Create New': '새로 작성',
  'Creator': '창조자',
  'Curve': '부드러운 관련선',
  'Curve/Line': '부드러운/곧은 관련선',
  'Cut': '자르기',
  'Dashed': '파선',
  'Date': '날짜',
  'Date Picker': '날짜 지정',
  'defined by': '만듦',
  'Delete': '삭제',
  'Deleting information': '삭제중입니다',
  'Dialog': '대화',
  'Diameter': '직경',
  'Do you want create new note?': '신규 노트를 작성하겠습니까?',
  'Dotted': '점선',
  'Download': '다운로드',
  'Downloading information': '다운로드 중입니다',
  'Drawing Mode': '그리기 모드',
  'Dynamic Drawing': '움직이는 그리기',
  'e-Book List': '서적일람',
  'e-Books': '전자서고',
  'Edge': '관련선',
  'Edge Shape': '선 종류',
  'Edit': '편집',
  'Edit(s) has been made.': '편집이 완료되었습니다',
  'Do you want to save edit(s)?': '수정 사항을 저장 하시겠습니까?',
  'Edit Flock': '그룹 편집',
  'Edit Memo': '메모지 편집',
  'Edit Style': '스타일 편집',
  'Editable Mode': '편집모드',
  'Editing': '편집중',
  'Erase': '삭제',
  'Failed': '업로드 실패',
  'File Deleted': '파일 삭제',
  'File Upload': '파일 업로드',
  'Filter': '필터링 표시',
  'Filter Association': '관련선을 필터링',
  'Filter Topic': '토픽 필터링',
  'Find': '찾기',
  'Fixation': '재배치',
  'Flock': '그룹',
  'Font': '글꼴',
  'Force All Fixed': '모두 고정',
  'Forgot Password?': '패스워드를 잊으셨나요?',
  'Free Mode': '배치:유동모드',
  'Get Selected Content Style': '선택한 컨텐츠의 스타일 취득하기',
  'Get Selected Edge Style': '선택한 선의 스타일 취득하기',
  'Get Style of Selected Item': '선택한 대상의 스타일 취득하기',
  'Go to': '이동',
  'Green Memo': '녹색 메모지',
  'Group': '그룹',
  'Height': '높이',
  'Hidden': '감추기',
  'Hide': '감추기',
  'Hide All': '모두 감추기',
  'Hide Memo': '메모지 감추기',
  'Hide Names': '작성자명 감추기',
  'Horizontal Axis': '수평축 작성',
  'Horizontal Equal': '좌우로 정렬',
  'Image': '이미지',
  'In case you cannot load iframe contents': 'iframe의 내용을 표시할 수 없을 때에는',
  'Introduction': '설명',
  'item(s) listed below': '토픽(컨텐츠)(아래에 보입니다)',
  'Join': '그룹에 추가',
  'Keyword': '키워드',
  'Label': '레이블',
  'Layout Topics': '토픽 배치',
  'Leave': '그룹에서 제외',
  'List': '일람',
  'List of Notebooks': '노트 일람',
  'Load': '불러오기',
  'Loading information': '불러오는 중입니다',
  'Local editing mode': '오프라인 편집모드',
  'Login': '로그인',
  'LOGIN FAILED': '로그인 불가',
  'Logout': '로그아웃',
  'maximum size is': '이미지의 최대 사이즈는',
  'members': '그룹 멤버',
  'Memo': '메모지',
  'Merge': '병합',
  'Miniature': '축소도',
  'Miniature Canvas': '축소도 보이기/감추기',
  'minimum size is': '이미지의 최소 사이즈는',
  'Model': '노트',
  'More': '다음',
  'Multiple Lines': '여러 줄',
  'Name': '이름',
  'New': '새로운',
  'New Axis': '새로운 축',
  'New Child Topic': '신규 부속 토픽',
  'New Citation': '신규 인용',
  'Add Resource': '신규 컨텐츠',
  'New Flock': '신규 그룹',
  'Add Memo': '메모지 작성',
  'New Note': '작성',
  'New Page': '페이지 작성',
  'New Topic': '신규 토픽',
  'Not Found.': '찾을 수 없습니다',
  'Not Owner': '작성자가 아닙니다',
  'Note': '주기',
  'Notebook': '노트',
  'Notebook name': '노트 이름',
  'Notebook saved in cloud as': '노트를 클라우드에 보존했습니다',
  'Notice': '알림',
  'Open': '열기',
  'ELLIPSE': '타원',
  'Overwrite': '덮어쓰기',
  'Page Name': '이름',
  'Pages': '페이지 조작',
  'Password': '패스워드',
  'Paste': '붙이기',
  'Pause': '정지',
  'Pink Memo': '분홍색 메모지',
  'Play': '유동',
  'Please log in.': '로그인 해주세요',
  'Please save': '저장해 주세요',
  'please wait': '잠시 기다려 주세요',
  'Post Page to Chat': '공동작업 내용을 등록중입니다',
  'Post This Page': '페이지 공개',
  'Presentation': '프레젠테이션',
  'Prev': '앞',
  'Private': '비공개',
  'Project': '프로젝트',
  'Public': '공개',
  'PUBLIC Notebooks': '공개 노트',
  'Radius': '반지름',
  'Randomize Layout': '랜덤 배치',
  'RECTANGLE': '사각형',
  'Redo': '다시 실행',
  'Reference': '출전',
  'Reflesh Chat Nodes': '공동작업 내용을 갱신중입니다',
  'Refresh': '갱신',
  'Registered Site': '등록한 사이트',
  'Release All Fixed': '모두 해방',
  'Relevant Page': '해당 페이지',
  'Reload': '페이지 다시 읽기(갱신)',
  'Reset View': '중앙으로 배치',
  'Reverse': '역방향',
  'Role': '역할',
  'Root': '루트',
  'ROUNDED': '각진 원',
  'SAMBUICHI PEs Office': '삼부이치 기술사 사무소',
  'Save': '저장',
  'Save As': '다른 이름으로 저장',
  'Save New': '신규 등록',
  'Save Notebook': '저장',
  'Scatter': '그룹 해제',
  'Scope': '범위',
  'Screenshot': '화면을 인쇄',
  'Search': '검색',
  'Search Filter': '검색문자열',
  'Search occurrence for the given (sub)string.': '검색문자열을 포함한 컨텐츠를 검색합니다',
  'Search the note for the given (sub)string.': '검색문자열을 포함한 토픽 후보를 필터링합니다',
  'Search topic for the given (sub)string.': '검색문자열을 포함한 토픽을 검색합니다',
  'Select': '선택',
  'Select All': '모두 선택',
  'Select Content': '컨텐츠를 선택',
  'Select Topic': '토픽을 선택',
  'separated with spaces': '공백으로 분할',
  'Setting Options': '옵션 설정',
  'Shape': '모양',
  'Short Cuts': '단축키 표시',
  'Shortcut Keys': '단축키 표시',
  'Show': '보이기',
  'Show All': '모두 보이기',
  'Size': '크기',
  'Solid': '선',
  'Start': '시작',
  'Static Drawing': '움직임 없이 그리기',
  'Straight': '곧은 관련선',
  'Subwindow': '실제 컨텐츠',
  'Text': '문자',
  'Text Color': '문자색',
  'Text File': '텍스트 파일',
  'The notebook was deleted successfully.': '노트를 삭제했습니다',
  'The selected notebook could not be deleted from the cloud service!': '클라우드에서 노트를 삭제할 수 없습니다',
  'The selected notebook could not be loaded from the cloud service!': '노트를 클라우드에서 불러올 수 없습니다',
  'This is the Navigation Window.': '이것은 화면 이동용 창입니다. 여기에는 항상 노트 전체가 표시됩니다.\n현재 보이는 화면 범위는 붉은선의 틀로 표시되며, 클릭하면 그쪽에 화면 중앙이 배치됩니다.',
  'THUMBNAIL': '미리보기 이미지',
  'Timemachine': '갱신 이력',
  'Toggle': '표시 전환',
  'Toggle Anchor': '고정/유동',
  'Toggle Chat': '시작・종료',
  'Toggle Fix': '고정/유동',
  'Toggle Search': '검색 보이기/감추기',
  'Topic': '토픽',
  'Topic Categoly': '카테고리',
  'Topics ': '토픽',
  'Tree': '계층',
  'Try again after logging in': '로그인한 뒤에 다시 실행해주세요',
  'Tutorial': '튜토리얼',
  'Type': '종류',
  'Un/Directed': '방향에 따라 펼치기 제한/하지않기',
  'undefined': '정의되지 않은',
  'Undirected Bloom': '방향없이 펼치기',
  'Undo': '원래대로 돌리기',
  'Upload': '업로드',
  'Upload File': '파일 업로드',
  'Upload Model ': '업로드',
  'Upload Pdf Annotations': 'PDF주석 업로드',
  'Uploaded': '업로드 완료',
  'URL': 'URL',
  'User ID': '사용자ID',
  'User Name': '작성자명 표시',
  'Vertical Equal Int.': '상하로 정렬',
  'View': '프레젠테이션',
  'Visible': '표시',
  'Width': '폭',
  'Wilt': '접기',
  'World Encyclopedia': '세계대백과사전',
  'WuWei & PDF Annotation': 'WuWei&PDF주석',
  'WuWei Manual': 'WuWei조작 매뉴얼',
  'WuWei Tutorial': 'WuWei조작 설명',
  'You are logged in as': '환영합니다',
  'You may try to tap SOURCE link to view contents directly.': '내용이 보이지 않을 때에는 대상 링크를 직접 클릭해주세요',
  'You need to log in before saving. Try to save again after logging in!': '노트를 저장하려면 로그인이 필요합니다. 로그인 후 다시 시도해 주세요',
  'You need to log in to reach your private notebooks': '비공개 노트를 사용하려면 로그인 해주세요',
  'You need to log in to use notebooks': '노트를 사용하려면 로그인 해주세요',
  'Your PRIVATE Notebooks': '비공개 노트',
  'Zoom': '줌',
  'Create a personal content collection and annotate it.': '개인 사용의 컨셉션을 스케치를 위해 사용합니다',
  'Visual notes will help you organize your thoughts.': '비주얼 노트는 당신의 생각을 정리하는 데 도움이됩니다'
};
