export const TW = {
  'erase' : '刪除',
  'expand': '開花',
  'collapse': '威爾特',
  'move' : '移動',
  'drag' : '移動',
  'and': '和',
  '-': '-',
  '+': '+',
  'Abbreviation': '縮寫',
  'About': '大約',
  'Add Content': '加入內容',
  'Add New Topic with Style of This Palette': '添加新的主題與此調色板風格',
  'Add Topic': '添加主題',
  'Adjust Size': '調整大小',
  'Align Horizontal': '對齊水平',
  'Align Vertical': '垂直對齊',
  'All': '所有',
  'Amoeba': '變形蟲',
  'Anchor': '錨',
  'Anchor Mode': '錨模式',
  'Angle': '角',
  'Anonymous Model': '匿名模式',
  'Anonyous': '匿名',
  'Any unsaved changes will be lost': '任何未保存的更改將丟失',
  'Are you absolutely sure you want to leave': '你真的確認要離開',
  'Are you sure you want to delete the following': '您確定要刪除以下',
  'Are you sure you want to delete this notebook?': '你確定你要刪除這台筆記本？',
  'Are you sure you want to merge': '你確定你要合併',
  'Arrow Head': '箭頭',
  'Associatins': 'Associatins',
  'Association': '聯想',
  'Association Role': '協會的作用',
  'AUGMENT': '擴大',
  'Blank': '空白',
  'Bloom': '開花',
  'Bloom All Direction': '布魯姆所有方向',
  'Bloom by Direction': '布魯姆通過方向',
  'Blue Memo': '藍備忘錄',
  'Cancel': '取消',
  'Close': '關閉',
  'Change': '變化',
  'Change Password': '更改密碼',
  'Chat Mode': '聊天模式',
  'CIRCLE': '圈',
  'Citation': '引文',
  'Class': '類',
  'Clear': '明確',
  'Clear Chat Nodes': '清除聊天節點',
  'Clear Screen': '清除屏幕',
  'Clear Selection': '清除選擇',
  'Clone': '克隆',
  'Cloud mode editing': '雲模式編輯',
  'Collabolation': 'Collabolation',
  'Color': '顏色',
  'COMMIT': 'COMMIT',
  'Content': '內容',
  'Resource': '內容',
  'CONTENTS URL': '內容URL',
  'Control Buttons': '控制按鈕',
  'Copy': '複製',
  'Copy & Paste': '複製和粘貼',
  'Copyright': '版權',
  'Create & Edit': '創建和編輯',
  'Create Account': '創建賬戶',
  'Create New': '新',
  'Creator': '創造者',
  'Curve': '曲線',
  'Curve/Line': '曲線/線',
  'Cut': '切',
  'Dashed': '虛線',
  'Date': '日期',
  'Date Picker': '日期選取器',
  'defined by': '通過定義',
  'Delete': '刪除',
  'Deleting information': '刪除信息',
  'Dialog': '對話',
  'Diameter': '直徑',
  'Do you want create new note?': '你確定你要做出新的筆記本電腦？',
  'Dotted': '點',
  'Download': '下載',
  'Downloading information': '下載信息',
  'Drawing Mode': '繪圖模式',
  'Dynamic Drawing': '動態圖',
  'e-Book List': '電子書列表',
  'e-Books': '電子書',
  'Edge': '邊緣',
  'Edge Shape': '邊緣形狀',
  'Edit': '編輯',
  'Edit(s) has been made.': '编辑已完成',
  'Do you want to save edit(s)?': '你想保存编辑吗？',
  'Edit Flock': '編輯羊群',
  'Edit Memo': '編輯備註',
  'Edit Style': '編輯樣式',
  'Editable Mode': '編輯模式',
  'Editing': '編輯',
  'Erase': '抹去',
  'Failed': '失敗',
  'File Deleted': '文件中刪除',
  'File Upload': '文件上傳',
  'Filter': '過濾器',
  'Filter Association': '過濾器協會',
  'Filter Topic': '過濾器主題',
  'Find': '發現',
  'Fixation': '固定術',
  'Flock': '群',
  'Font': '字形',
  'Force All Fixed': '強制所有固定',
  'Forgot Password?': '忘記密碼？',
  'Free Mode': '免費模式',
  'Get Selected Content Style': '獲取所選內容風格',
  'Get Selected Edge Style': '獲取選邊樣式',
  'Get Style of Selected Item': '獲取所選項目的風格',
  'Go to': '到',
  'Green Memo': '綠色備忘錄',
  'Group': '組',
  'Height': '高度',
  'Hidden': '隱',
  'Hide': '隱藏',
  'Hide All': '全部隱藏',
  'Hide Memo': '隱藏備忘錄',
  'Hide Names': '隱藏名稱',
  'Horizontal Axis': '水平軸',
  'Horizontal Equal': '橫向平等',
  'Image': '圖像',
  'In case you cannot load iframe contents': '如果您不能加載的iframe內容',
  'Introduction': '介紹',
  'item(s) listed below': '下面列出的項目（S）',
  'Join': '加入',
  'Keyword': '關鍵詞',
  'Label': '標籤',
  'Layout Topics': '版面主題',
  'Leave': '離開',
  'List': '名單',
  'List of Notebooks': '筆記本一覽',
  'Load': '加載',
  'Loading information': '加載信息',
  'Local editing mode': '本地編輯模式',
  'Login': '登錄',
  'LOGIN FAILED': '登錄失敗',
  'Logout': '註銷',
  'maximum size is': '最大尺寸為',
  'members': '成員',
  'Memo': '備忘錄',
  'Merge': '合併',
  'Miniature': '微型',
  'Miniature Canvas': '微型帆布',
  'minimum size is': '最小尺寸是',
  'Model': '型號',
  'More': '更多',
  'Multiple Lines': '多行',
  'Name': '名字',
  'New': '新',
  'New Axis': '新中軸線',
  'New Child Topic': '新的兒童主題',
  'New Citation': '新引',
  'Add Resource': '新的內容',
  'New Flock': '新的羊群',
  'Add Memo': '新的備忘錄',
  'New Note': '新',
  'New Page': '新頁面',
  'New Topic': '新主題',
  'Not Found.': '未找到',
  'Not Owner': '沒有業主',
  'Note': '注意',
  'Notebook': '筆記本',
  'Notebook name': '筆記本電腦的名字',
  'Notebook saved in cloud as': '筆記本電腦保存在雲中',
  'Notice': '通知',
  'Open': '打開',
  'ELLIPSE': '橢圓形',
  'Overwrite': '覆蓋',
  'Page Name': '頁的備忘錄',
  'Pages': '網頁',
  'Password': '密碼',
  'Paste': '貼',
  'Pause': '暫停',
  'Pink Memo': '粉紅色的備忘錄',
  'Play': '玩',
  'Please log in.': '請登錄。',
  'Please save': '請妥善保存',
  'please wait': '請稍候',
  'Post Page to Chat': '帖子頁聊天',
  'Post This Page': '發布此頁',
  'Presentation': '介紹',
  'Prev': '上一頁',
  'Private': '私人',
  'Project': '工程',
  'Public': '公開',
  'PUBLIC Notebooks': 'PUBLIC筆記本電腦',
  'Radius': '半徑',
  'Randomize Layout': '佈局隨機化',
  'RECTANGLE': '矩形',
  'Redo': '重做',
  'Reference': '參考',
  'Reflesh Chat Nodes': 'Reflesh聊天節點',
  'Refresh': '刷新',
  'Registered Site': '註冊網站',
  'Release All Fixed': '釋放所有固定',
  'Relevant Page': '相關頁面',
  'Reload': '刷新',
  'Reset View': '重置瀏覽',
  'Reverse': '反',
  'Role': '角色',
  'Root': '根',
  'ROUNDED': '圓角',
  'SAMBUICHI PEs Office': 'SAMBUICHI PE辦公室',
  'Save': '保存',
  'Save As': '保存為',
  'Save New': '保存新',
  'Save Notebook': '保存筆記本',
  'Scatter': '分散',
  'Scope': '範圍',
  'Screenshot': '截圖',
  'Search': '搜索',
  'Search Filter': ' 搜索過濾器',
  'Search occurrence for the given (sub)string.': '搜索事件為給定的（子）字符串。',
  'Search the note for the given (sub)string.': '搜索注意對於給定的（子）字符串。',
  'Search topic for the given (sub)string.': '搜索話題，給定（子）字符串。',
  'Select': '選擇',
  'Select All': '全選',
  'Select Content': '選擇內容',
  'Select Topic': '選擇主題',
  'separated with spaces': '用空格隔開',
  'Setting Options': '設置選項',
  'Shape': '形狀',
  'Short Cuts': '捷徑',
  'Shortcut Keys': '快捷鍵',
  'Show': '演出',
  'Show All': '顯示全部',
  'Size': '尺寸',
  'Solid': '固',
  'Start': '開始',
  'Static Drawing': '靜態圖',
  'Straight': '直行',
  'Subwindow': '子窗口',
  'Text': '文本',
  'Text Color': '文字顏色',
  'Text File': '文字檔',
  'The notebook was deleted successfully.': '筆記本電腦被成功刪除。',
  'The selected notebook could not be deleted from the cloud service!': '所選擇的筆記本電腦無法從雲服務中刪除！',
  'The selected notebook could not be loaded from the cloud service!': '所選的筆記本無法從雲服務裝！',
  'This is the Navigation Window.': '這是導航窗口。\ n它總是由\鈉紅色輪廓顯示整個筆記本\ nwith顯示當前視口。點擊\ n移動視口。',
  'THUMBNAIL': '縮略圖',
  'Timemachine': '時間機器',
  'Toggle': '切換',
  'Toggle Anchor': '切換錨',
  'Toggle Chat': '切換聊天',
  'Toggle Fix': '切換修復',
  'Toggle Search': '切換搜索',
  'Topic': '話題',
  'Topic Categoly': '主題分類',
  'Topics ': '主題',
  'Tree': '樹',
  'Try again after logging in': '登錄後再試',
  'Tutorial': '教程',
  'Type': '類型',
  'Un/Directed': 'UN /導演',
  'undefined': '未定義',
  'Undirected Bloom': '無向布魯姆',
  'Undo': '復原',
  'Upload': '上傳',
  'Upload File': '上傳文件',
  'Upload Model ': '上傳模式',
  'Upload Pdf Annotations': '上傳PDF註釋',
  'Uploaded': '上傳',
  'URL': 'URL',
  'User ID': '用戶身份',
  'User Name': '用戶名',
  'Vertical Equal Int.': '縱向平等詮釋。',
  'View': '視圖',
  'Visible': '可見',
  'Width': '寬度',
  'Wilt': '威爾特',
  'World Encyclopedia': '世界百科全書',
  'WuWei & PDF Annotation': '無為和PDF註釋',
  'WuWei Manual': '無為手冊',
  'WuWei Tutorial': '無為教程',
  'You are logged in as': '您的登錄身份',
  'You may try to tap SOURCE link to view contents directly.': '您可以嘗試挖掘源鏈接，直接查看內容。',
  'You need to log in before saving. Try to save again after logging in!': '您需要在保存之前登錄。嘗試登錄後再次保存！',
  'You need to log in to reach your private notebooks': '您需要登錄到您的私人筆記本電腦',
  'You need to log in to use notebooks': '您需要登錄才能使用筆記本電腦',
  'Your PRIVATE Notebooks': '你的私人筆記本電腦',
  'Zoom': '放大',
  'Create a personal content collection and annotate it.': '創建個人內容集並對其進行註釋',
  'Visual notes will help you organize your thoughts.': '視覺筆記將幫助您組織您的想法'
};
